export interface Product {
  id: number;
  name: string;
  category: string;
  gender: "Men" | "Women" | "Kids" | "Unisex";
  price: number;
  originalPrice?: number;
  image: string;
  images?: string[];
  description: string;
  sizes: string[];
  colors: string[];
  rating: number;
  reviews: number;
  brand: string;
  inStock: boolean;
  isNew?: boolean;
  isBestseller?: boolean;
}

export const PRODUCTS: Product[] = [
  // OUTERWEAR
  {
    id: 1,
    name: "Overcast Wool Bomber",
    category: "Outerwear",
    gender: "Men",
    price: 12499,
    originalPrice: 15999,
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=1000&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1617114917202-abc239b7923e?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "A premium wool-blend bomber crafted for the urban explorer. Features our signature structured shoulder silhouette with ribbed cuffs and hem. Fully lined with our signature ROAZ satin lining.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Charcoal", "Oatmeal", "Black"],
    rating: 4.8,
    reviews: 124,
    brand: "ROAZ",
    inStock: true,
    isBestseller: true,
  },
  {
    id: 2,
    name: "Crimson Suede Trucker",
    category: "Outerwear",
    gender: "Men",
    price: 14999,
    image: "/crimson-trucker.png",
    images: [
      "/crimson-trucker.png",
      "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "A bold suede trucker jacket with a relaxed fit. Featuring contrast stitching and a classic western-inspired yoke.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Crimson", "Tan", "Navy"],
    rating: 4.6,
    reviews: 88,
    brand: "ROAZ",
    inStock: true,
    isNew: true,
  },
  {
    id: 3,
    name: "Shadow Peacoat Hoodie",
    category: "Outerwear",
    gender: "Unisex",
    price: 16999,
    image: "https://images.unsplash.com/photo-1620799139507-2a76f79a2f4d?q=80&w=1000&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1620799139507-2a76f79a2f4d?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1556821840-3a63f95609a7?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "A hybrid between a classic peacoat and an oversized hoodie. Double-face wool exterior with a drawstring hood and concealed button closure.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Slate"],
    rating: 4.9,
    reviews: 210,
    brand: "ROAZ",
    inStock: true,
    isBestseller: true,
  },
  {
    id: 4,
    name: "Oatmeal Suede Jacket",
    category: "Outerwear",
    gender: "Women",
    price: 13499,
    originalPrice: 17000,
    image: "/oatmeal-jacket.png",
    images: ["/oatmeal-jacket.png"],
    description: "A refined suede jacket in a warm oatmeal tone. Soft silhouette with a clean notch collar and side-seam pockets.",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Oatmeal", "Ivory"],
    rating: 4.7,
    reviews: 63,
    brand: "ROAZ",
    inStock: true,
  },
  {
    id: 13,
    name: "Strata Quilted Vest",
    category: "Outerwear",
    gender: "Unisex",
    price: 9499,
    image: "/quilted-vest.png",
    images: ["/quilted-vest.png"],
    description: "A sleek quilted vest with horizontal baffle stitching. Lightweight insulation for transitional weather.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Forest Green", "Burgundy"],
    rating: 4.5,
    reviews: 47,
    brand: "ROAZ",
    inStock: false,
    isNew: true,
  },

  // APPAREL
  {
    id: 7,
    name: "Tribal Graphic Knit",
    category: "Apparel",
    gender: "Unisex",
    price: 8999,
    image: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?q=80&w=1000&auto=format&fit=crop"],
    description: "An oversized knit pullover with a hand-drawn tribal graphic print across the chest. Heavy-gauge cotton construction.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Ecru", "Black", "Rust"],
    rating: 4.6,
    reviews: 95,
    brand: "ROAZ",
    inStock: true,
  },
  {
    id: 8,
    name: "Zenith Oversized Hoodie",
    category: "Apparel",
    gender: "Unisex",
    price: 6499,
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1556821840-3a63f95609a7?q=80&w=1000&auto=format&fit=crop"],
    description: "A garment-dyed, 400gsm heavyweight French terry hoodie. Drop shoulder construction with a kangaroo pocket.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Washed Black", "Sage", "Vintage White"],
    rating: 4.9,
    reviews: 342,
    brand: "ROAZ",
    inStock: true,
    isBestseller: true,
  },
  {
    id: 10,
    name: "Monolith Relaxed Tee",
    category: "Apparel",
    gender: "Unisex",
    price: 2999,
    image: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=1000&auto=format&fit=crop"],
    description: "A boxy-cut tee with a slight elongated back hem. Printed with the ROAZ monolith graphic. 200gsm combed cotton.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["White", "Black", "Slate"],
    rating: 4.7,
    reviews: 180,
    brand: "ROAZ",
    inStock: true,
    isBestseller: true,
  },
  {
    id: 14,
    name: "Flow Linen Shirt",
    category: "Apparel",
    gender: "Men",
    price: 4899,
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=1000&auto=format&fit=crop"],
    description: "Relaxed fit linen shirt for the warmer months. Camp collar and an extended back hem. 100% pure linen.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Sand", "Sky Blue", "Olive"],
    rating: 4.5,
    reviews: 71,
    brand: "ROAZ",
    inStock: true,
    isNew: true,
  },
  {
    id: 16,
    name: "Vanguard Tech Layer",
    category: "Apparel",
    gender: "Unisex",
    price: 5499,
    image: "/tech-layer.png",
    images: ["/tech-layer.png"],
    description: "A moisture-wicking tech long-sleeve with a clean structured look. Features a hidden chest zip pocket.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Cobalt"],
    rating: 4.4,
    reviews: 52,
    brand: "ROAZ",
    inStock: true,
  },

  // BOTTOMS
  {
    id: 5,
    name: "Core Sweatpants Black",
    category: "Bottoms",
    gender: "Unisex",
    price: 4899,
    image: "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1506629082955-511b1aa562c8?q=80&w=1000&auto=format&fit=crop"],
    description: "Our signature heavyweight sweatpants. Tapered leg with a ribbed ankle cuff. 420gsm brushed fleece interior.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black"],
    rating: 4.8,
    reviews: 260,
    brand: "ROAZ",
    inStock: true,
    isBestseller: true,
  },
  {
    id: 6,
    name: "Core Sweatpants Moss",
    category: "Bottoms",
    gender: "Unisex",
    price: 4899,
    image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=1000&auto=format&fit=crop"],
    description: "The same premium sweatpant silhouette in a muted moss colorway. Perfect for tonal street styling.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Moss"],
    rating: 4.7,
    reviews: 143,
    brand: "ROAZ",
    inStock: true,
  },
  {
    id: 9,
    name: "Utility Cargo Trousers",
    category: "Bottoms",
    gender: "Men",
    price: 7299,
    image: "/utility-cargo.png",
    images: ["/utility-cargo.png"],
    description: "Six-pocket cargo trousers with a relaxed wide-leg cut. Adjustable ankle straps and ripstop nylon construction.",
    sizes: ["S", "M", "L", "XL", "28", "30", "32", "34"],
    colors: ["Khaki", "Black", "Stone"],
    rating: 4.6,
    reviews: 117,
    brand: "ROAZ",
    inStock: true,
    isNew: true,
  },
  {
    id: 15,
    name: "Traction Tech Shorts",
    category: "Bottoms",
    gender: "Unisex",
    price: 3999,
    image: "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1591195853828-11db59a44f6b?q=80&w=1000&auto=format&fit=crop"],
    description: "Lightweight, quick-dry performance shorts with a 7\" inseam and zippered side pockets.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Forest"],
    rating: 4.5,
    reviews: 89,
    brand: "ROAZ",
    inStock: true,
  },
  {
    id: 17,
    name: "Arid Desert Cargo",
    category: "Bottoms",
    gender: "Men",
    price: 6499,
    image: "/desert-cargo.png",
    images: ["/desert-cargo.png"],
    description: "Inspired by desert-worn utility wear. Washed linen-cotton blend with oversized patch pockets.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Sand", "Desert Rose", "Khaki"],
    rating: 4.4,
    reviews: 34,
    brand: "ROAZ",
    inStock: false,
  },

  // ACCESSORIES
  {
    id: 11,
    name: "Draft Canvas Tote",
    category: "Accessories",
    gender: "Unisex",
    price: 2199,
    image: "https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=1000&auto=format&fit=crop"],
    description: "A heavyweight canvas tote with a wide gusset and reinforced handles. Screen printed with the ROAZ Drafts logo.",
    sizes: ["One Size"],
    colors: ["Natural", "Black", "Olive"],
    rating: 4.7,
    reviews: 98,
    brand: "ROAZ",
    inStock: true,
  },
  {
    id: 12,
    name: "Vector Beanie Slate",
    category: "Accessories",
    gender: "Unisex",
    price: 1499,
    image: "https://images.unsplash.com/photo-1576871337622-98d48d1cf531?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1576871337622-98d48d1cf531?q=80&w=1000&auto=format&fit=crop"],
    description: "A fine-knit merino wool beanie with a slight slouch. Embroidered ROAZ vector logo on the cuff.",
    sizes: ["One Size"],
    colors: ["Slate", "Black", "Cream"],
    rating: 4.8,
    reviews: 76,
    brand: "ROAZ",
    inStock: true,
    isBestseller: true,
  },
  {
    id: 18,
    name: "Architect Monogram Cap",
    category: "Accessories",
    gender: "Unisex",
    price: 1899,
    image: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1588850561407-ed78c282e89b?q=80&w=1000&auto=format&fit=crop"],
    description: "A 6-panel structured cap with a tonal embroidered ROAZ Architect logo. Adjustable clip closure.",
    sizes: ["One Size"],
    colors: ["Black", "Khaki", "White"],
    rating: 4.6,
    reviews: 55,
    brand: "ROAZ",
    inStock: true,
    isNew: true,
  },
  {
    id: 19,
    name: "Nexus Utility Belt",
    category: "Accessories",
    gender: "Unisex",
    price: 3299,
    image: "https://images.unsplash.com/photo-1598532163257-ae3c6b250700?q=80&w=1000&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1598532163257-ae3c6b250700?q=80&w=1000&auto=format&fit=crop"],
    description: "A dual-buckle utility belt in ROAZ's signature matte hardware finish. Full-grain leather construction.",
    sizes: ["S/M", "L/XL"],
    colors: ["Black", "Tan"],
    rating: 4.5,
    reviews: 29,
    brand: "ROAZ",
    inStock: true,
  },
];

export const CATEGORIES = ["Outerwear", "Apparel", "Bottoms", "Accessories"];
export const GENDERS = ["Men", "Women", "Kids", "Unisex"];

export const formatPrice = (price: number) =>
  `₹${price.toLocaleString("en-IN")}`;
